import 'package:flutter/material.dart';
import 'package:flutter_advanced_switch/flutter_advanced_switch.dart';
import 'package:leaps_frontend/utils/colors.dart';
import 'package:remixicon/remixicon.dart';
import 'package:intl/intl.dart';

class SearchLocationScreen extends StatefulWidget {
  const SearchLocationScreen({super.key});
  static const routeName = '/search_location';

  @override
  State<SearchLocationScreen> createState() => _SearchLocationScreenState();
}

class _SearchLocationScreenState extends State<SearchLocationScreen> {
  List<String> locations = [
    'New York, NY',
    'Los Angeles, CA',
    'Chicago, IL',
    'Houston, TX',
    'Phoenix, AZ',
    'Philadelphia, PA',
    'San Antonio, TX',
    'San Diego, CA',
    'Dallas, TX',
    'San Jose, CA',
    'Austin, TX',
    'Jacksonville, FL',
    'San Francisco, CA',
    'Columbus, OH',
    'Indianapolis, IN',
    'Fort Worth, TX',
    'Charlotte, NC',
    'Seattle, WA',
    'Denver, CO',
    'Washington, DC',
    'Boston, MA',
    'Nashville, TN',
    'Baltimore, MD',
    'Oklahoma City, OK',
    'Louisville, KY',
    'Portland, OR',
    'Las Vegas, NV',
    'Milwaukee, WI',
    'Albuquerque, NM',
    'Tucson, AZ',
    'Fresno, CA',
    'Sacramento, CA',
    'Long Beach, CA',
    'Kansas City, MO',
    'Mesa, AZ',
    'Atlanta, GA',
    'Colorado Springs, CO',
    'Raleigh, NC',
    'Omaha, NE',
    'Miami, FL',
    'Tampa, FL',
    'Minneapolis, MN',
    'Honolulu, HI',
    'Arlington, TX',
    'Wichita, KS',
    'New Orleans, LA',
    'Bakersfield, CA',
    'Tulsa, OK',
    'Aurora, CO',
    'Santa Ana, CA',
    'St. Louis, MO',
    'Riverside, CA',
    'Corpus Christi, TX',
    'Lexington, KY',
    'Pittsburgh, PA',
    'Anchorage, AK',
    'Stockton, CA',
    'Cincinnati, OH',
    'St. Paul, MN',
    'Toledo, OH',
    'Newark, NJ',
    'Greensboro, NC',
    'Plano, TX',
    'Henderson, NV',
    'Lincoln, NE',
    'Buffalo, NY',
    'Jersey City, NJ',
    'Chula Vista, CA',
    'Fort Wayne, IN',
    'Orlando, FL',
    'St. Petersburg, FL',
    'Chandler, AZ',
    'Laredo, TX',
    'Norfolk, VA',
    'Durham, NC',
    'Madison, WI',
    'Lubbock, TX',
    'Irvine, CA',
    'Winston-Salem, NC',
    'Glendale, AZ',
    'Garland, TX',
    'Hialeah, FL',
    'Reno, NV',
    'Chesapeake, VA',
    'Gilbert, AZ',
    'Baton Rouge, LA',
    'Irving, TX',
    'Scottsdale, AZ',
    'North Las Vegas, NV',
    'Fremont, CA',
    'Boise, ID',
    'Richmond, VA',
    'San Bernardino, CA',
    'Birmingham, AL',
    'Spokane, WA',
    'Rochester, NY',
    'Des Moines, IA',
    'Modesto, CA',
    'Fayetteville, NC',
    'Tacoma, WA',
    'Oxnard, CA',
    'Fontana, CA',
    'Columbus, GA',
    'Montgomery, AL',
    'Moreno Valley, CA',
    'Shreveport, LA',
    'Aurora, IL',
    'Yonkers, NY',
    'Akron, OH',
    'Huntington Beach, CA',
    'Little Rock, AR',
    'Augusta, GA',
    'Amarillo, TX',
    'Glendale, CA',
    'Mobile, AL',
    'Grand Rapids, MI',
    'Salt Lake City, UT',
    'Tallahassee, FL',
    'Huntsville, AL',
    'Grand Prairie, TX',
    'Knoxville, TN',
    'Worcester, MA',
    'Newport News, VA',
    'Brownsville, TX',
    'Overland Park, KS',
    'Santa Clarita, CA',
    'Providence, RI',
    'Garden Grove, CA',
    'Chattanooga, TN',
    'Oceanside, CA',
    'Jackson, MS',
    'Fort Lauderdale, FL',
    'Santa Rosa, CA',
    'Rancho Cucamonga, CA',
    'Port St. Lucie, FL',
    'Tempe, AZ',
    'Ontario, CA',
    'Vancouver, WA',
    'Cape Coral, FL',
    'Sioux Falls, SD',
    'Springfield, MO',
    'Peoria, AZ',
    'Pembroke Pines, FL',
    'Elk Grove, CA',
    'Salem, OR',
    'Lancaster, CA',
    'Corona, CA',
    'Eugene, OR',
    'Palmdale, CA',
    'Salinas, CA',
    'Springfield, MA',
    'Pasadena, TX',
    'Fort Collins, CO',
    'Hayward, CA',
    'Pomona, CA',
    'Cary, NC',
    'Rockford, IL',
    'Alexandria, VA',
    'Escondido, CA',
    'McKinney, TX',
    'Kansas City, KS',
    'Joliet, IL',
    'Sunnyvale, CA',
    'Torrance, CA',
    'Bridgeport, CT',
    'Lakewood, CO',
    'Hollywood, FL',
    'Paterson, NJ',
    'Naperville, IL',
    'Syracuse, NY',
    'Mesquite, TX',
    'Dayton, OH',
    'Savannah, GA',
    'Clarksville, TN',
    'Orange, CA',
    'Pasadena, CA',
    'Fullerton, CA',
    'Killeen, TX',
    'Frisco, TX',
    'Hampton, VA',
    'McAllen, TX',
    'Warren, MI',
    'Bellevue, WA',
    'West Valley City, UT',
    'Columbia, SC',
    'Olathe, KS',
    'Sterling Heights, MI',
    'New Haven, CT',
    'Miramar, FL',
    'Waco, TX',
    'Thousand Oaks, CA',
    'Cedar Rapids, IA',
    'Charleston, SC',
    'Visalia, CA',
    'Topeka, KS',
    'Elizabeth, NJ',
    'Gainesville, FL',
    'Thornton, CO',
    'Roseville, CA',
    'Carrollton, TX',
    'Coral Springs, FL',
    'Stamford, CT',
    'Simi Valley, CA',
    'Concord, CA',
  ];

  @override
  void initState() {
    filteredLocations = locations;
    super.initState();
  }

  void _filterLocations(String query) {
    setState(() {
      filteredLocations = locations
          .where((location) =>
              location.toLowerCase().contains(query.toLowerCase()))
          .toList();
    });
  }

  List<String> filteredLocations = [];

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: primaryBackgroundColor,
      appBar: AppBar(
        backgroundColor: primaryBackgroundColor,
        title: const Text(
          'Your Team Location',
          style: TextStyle(color: Colors.black),
        ),
        iconTheme: const IconThemeData(color: Colors.black),
      ),
      body: Padding(
        padding: const EdgeInsets.all(16),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            TextField(
              onChanged: _filterLocations,
              decoration: InputDecoration(
                labelStyle: TextStyle(
                  color: Colors.black,
                ),
                enabledBorder: UnderlineInputBorder(
                  borderSide: BorderSide(color: borderColor),
                ),
                focusedBorder: UnderlineInputBorder(
                  borderSide: BorderSide(color: primaryColor),
                ),
                hintText: 'Search for a city or state',
                prefixIcon: Icon(Icons.search),
              ),
            ),
            SizedBox(height: 10),
            Expanded(
              child: ListView.builder(
                itemCount: filteredLocations.length,
                itemBuilder: (context, index) {
                  return ListTile(
                    title: Text(filteredLocations[index]),
                    onTap: () {},
                  );
                },
              ),
            ),
          ],
        ),
      ),
    );
  }
}
